src/blog/urls.py
"""
:created on: 2017-09-21

:author: Marcin Muszynski
:contact: marcinowski007@gmail.com
"""
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import ArticleDetail, ArticleList

urlpatterns = [
    url(r'^$', ArticleList.as_view(), name='main'),
    url(r'^(?P<slug>[\w-]+)$', ArticleDetail.as_view(), name='article'),
    url(r'^(?P<id>[0-9]+)$', ArticleDetail.as_view(), name='article'),
]

src/devmate/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import url, static, include
from django.contrib import admin
from django.views.generic import TemplateView

from blog.api import urls as api_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    url(r'', include('blog.urls', namespace='blog')),
    url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^projects/', TemplateView.as_view(template_name='projects.html'), name='projects'),
    prefix_default_language=True,
)

urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/blog/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.utils.text import slugify, Truncator
from django.utils.translation import ugettext_lazy as _

from blog.managers import ArticleManager
from blog.services import get_random_thumbnail, THUMBNAILS_DIR


UserModel = get_user_model()


class Tag(models.Model):
    tag = models.SlugField(unique=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')


class Article(models.Model):
    CONTENT_STATUS_DRAFT = 1
    CONTENT_STATUS_PUBLISHED = 2
    CONTENT_STATUS_CHOICES = (
        (CONTENT_STATUS_DRAFT, _("Draft")),
        (CONTENT_STATUS_PUBLISHED, _("Published")),
    )
    author = models.ForeignKey(UserModel, related_name='articles')
    related_posts = models.ManyToManyField("self", verbose_name="Related posts", blank=True)
    created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    content = models.TextField(_("Content"), blank=True)  # todo: Custom content field + widget
    description = models.TextField(_("Description"), blank=True)
    title = models.CharField(_("Title"), max_length=500)  # fixme: ugettext
    slug = models.SlugField(_("Slug"), max_length=500, blank=True)  # fixme: ugettext
    tags = GenericRelation(Tag, related_query_name='articles')
    thumbnail = models.ImageField(upload_to=THUMBNAILS_DIR, default=get_random_thumbnail)
    status = models.IntegerField(
        _("Status"),
        choices=CONTENT_STATUS_CHOICES,
        default=CONTENT_STATUS_PUBLISHED,
        help_text=_(
            "With Draft chosen, will only be shown for admin users "
            "on the site."
        )
    )
    publish_date = models.DateTimeField(
        _("Published from"),
        help_text=_("With Published chosen, won't be shown until this time"),
        blank=True,
        null=True,
        db_index=True
    )

    objects = ArticleManager()

    def save(self, *args, **kwargs):
        """ Makes sure that:
          - the slug is generated
          - the publish date is set
        """
        if not self.slug and self.title:
            self.slug = slugify(self.title)
        if not self.publish_date and self.status == self.CONTENT_STATUS_PUBLISHED:
            self.publish_date = datetime.now()
        if not self.description:
            self.description = Truncator(self.content).words(100, html=True)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:article', kwargs={'slug': self.slug})


class Image(models.Model):
    path = models.ImageField(upload_to='images/article_images/')


"""
https://sachinchoolur.github.io/angular-trix/
textangular.com
https://www.tinymce.com/  # not angular
https://github.com/summernote/angular-summernote
https://github.com/angular-ui/ui-tinymce
http://wanming.github.io/angular-editor/
"""

src/utils/models.py
from django.db import models

# Create your models here.

src/blog/forms.py
from django import forms

from .models import Article, Tag


class ArticleForm(forms.Form):
    tags = forms.MultipleChoiceField(
            choices=Tag.objects.values_list('tag', flat=True)
        )
    publish_date = forms.DateTimeField()
    content = forms.CharField(min_length=5)

src/blog/views.py
from django.views.generic import DetailView, ListView

from blog.forms import ArticleForm
from blog.models import Article


class ArticleDetail(DetailView):
    model = Article
    template_name = 'blog/article.html'
    lookup_field = 'slug'
    context_object_name = 'article'


class ArticleList(ListView):
    model = Article
    template_name = 'blog/main.html'
    context_object_name = 'articles'

    def get_queryset(self):
        return Article.objects.get_published()

src/utils/views.py
from django.shortcuts import render

# Create your views here.

src/blog/templates/blog/article.html
{% extends 'skeleton.html' %}

{% block landing %}
	<image-splash image="{{ article.thumbnail.url }}" splash-title="{{ article.title }}"></image-splash>
{% endblock landing %}
{% block content %}
	<md-content layout-padding>
		<div flex layout="column" layout-align="center center">
			<div style="max-width: 60%">
				{{ article.content }}
			</div>
		</div>
	</md-content>
{% endblock content %}

src/blog/templates/blog/main.html
{% extends 'skeleton.html' %}
{% load i18n staticfiles %}

{% block controller %}MainCtrl{% endblock controller %}

{% block landing %}
    <image-splash splash-title="DEVMATE" font-color="black" dim="0.0">
    </image-splash>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'site/js/main.js' %}"></script>
{% endblock extra_js %}

{% block content %}
    <md-content layout-padding>
        <div flex="100" layout="column" layout-align="center center">
            {% for article in articles %}
            <article-card img-url="{{ article.thumbnail.url }}">
                <article-title><a class="article-title-link" ng-href="{{article.get_absolute_url}}">{{ article.title }}</a></article-title>
                <article-date>{{ article.publish_date|date:"j E y" }}</article-date>
                <article-brief>{{ article.description }}</article-brief>
            </article-card>
            {% empty %}
                <h1>{% trans 'No articles has been added yet :(' %}</h1>
            {% endfor %}
        </div>
    </md-content>
{% endblock content %}

src/templates/about.html
{% extends 'skeleton.html' %}
{% load static i18n %}

{% block landing %}
    <image-splash flex image="{% static 'img/background.jpg' %}">
        <div flex layout="row" layout-align="center center">
            <h2 class="md-display-3" style="color: white;">{% trans 'O mnie' %}</h2>
        </div>
    </image-splash>
{% endblock landing %}

src/templates/directives.html
{# templates for angular directives #}
{% verbatim %}

<script type="text/ng-template" id="directives/stickyScroll.html">
    <button class="md-fab md-button md-ink-ripple" type="button" ng-click="scrollTop()" aria-label="Back to Top" ng-click="scrollTop()">
        <md-icon md-svg-src="img/icons/chevron-up.svg"></md-icon>
    </button>
</script>

<script type="text/ng-template" id="directives/articleCard.html">
	<div layout-margin style="height: 200px; width: 800px">
		<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url({{ imgUrl }});" ng-mouseenter="showDescription=true" ng-mouseleave="showDescription=false">
			<div class="card-title">
				<p ng-transclude="brief" class="articleCardDescription" ng-show="showDescription">No description for this article.</p>
				<p ng-transclude="date"></p>
				<p ng-transclude="title" style="font-size: 1.5em; padding: 0; margin: 0;"></p>
			</div>
		</div>
	</div>
</script>

<script type="text/ng-template" id="directives/articleList.html">
    <!-- TODO: not implemented -->
</script>

<script type="text/ng-template" id="directives/imageSplash.html">
	<div flex layout-fill layout="column" layout-align="center center">
        <svg height="100%" width="100%" style="margin-top: 100px;">
            <text x="50%" y="50%" font-family="Lato" fill="{{fontColor}}" text-anchor="middle" font-size="48">{{ splashTitle }}</text>
        </svg>
	</div>
</script>

<script type="text/ng-template" id="directives/navSearch.html">
    <md-button aria-label="search-box" ng-click="showInput = !showInput">
        <md-icon md-svg-src="img/icons/search.svg"></md-icon>
    </md-button>
    <md-input-container md-no-float class="md-block" ng-show="showInput">
	    <input placeholder="Address 2">
	    <md-icon md-svg-src="img/icons/tabs-arrow.svg" ng-click=""></md-icon>
    </md-input-container>
</script>

{% endverbatim %}

src/templates/main.html
{% extends 'skeleton.html' %}
{% load i18n staticfiles %}

{% block controller %}MainCtrl{% endblock controller %}

{% block landing %}
    <image-splash splash-title="DEVMATE" font-color="black" dim="0.0">
    </image-splash>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'site/js/main.js' %}"></script>
{% endblock extra_js %}

{% block content %}
    <md-content layout-padding>
        <div flex="100" layout="column" layout-align="center center">
            {% for article in articles %}
            <article-card img-url="{{ article.thumbnail.url }}">
                <article-title><a class="article-title-link" ng-href="{{article.get_absolute_url}}">{{ article.title }}</a></article-title>
                <article-date>{{ article.publish_date|date:"j E y" }}</article-date>
                <article-brief>{{ article.description }}</article-brief>
            </article-card>
            {% empty %}
                <h1>{% trans 'No articles has been added yet :(' %}</h1>
            {% endfor %}
            <md-progress-circular md-mode="indeterminate" class="md-warn" ng-show="progressCircular"></md-progress-circular>
            <md-button class="md-raised md-primary" ng-click="progressCircular = !progressCircular">
                {% trans 'Show more articles' %}
            </md-button>
        </div>
    </md-content>
{% endblock content %}

src/templates/projects.html
{% extends 'skeleton.html' %}
{% load staticfiles i18n %}

{% block landing %}
    <image-splash flex image="{% static 'img/background.jpg' %}" splash-title="{% trans 'Projects' %}">
    </image-splash>
{% endblock %}

src/templates/skeleton.html
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
{% load i18n staticfiles utils %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Marcin Muszynski">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
    <title>DevMate {% block title %}{% endblock title %}</title>
    <link href="{% static 'libs/angular-material/angular-material'|minified:'css' %}" rel="stylesheet">
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic"> -->
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% block extra_css %}{% endblock extra_css %}
</head>
<body ng-app="devMateApp" ng-controller="{% block controller %}SkeletonCtrl{% endblock controller %}" ng-cloak>
    <header flex="100">
        {% block header %}
        <div layout="column" layout-fill>
            <md-content>
                <md-toolbar md-scroll-shrink style="position: fixed; box-shadow: green 0px 2px 2px;" scroll-class scroll-offset="200" scroll-toggle-class="scrolled-navbar" flex layout="row" layout-align="space-around center">
                    <div class="md-toolbar-tools">
                        <md-button ng-href="{% url 'blog:main' %}">
                            <h3>{% trans 'Blog' %}</h3>
                        </md-button>
                        <md-button ng-href="{% url 'about' %}">
                            <h3>{% trans 'About me' %}</h3>
                        </md-button>
                        <md-button ng-href="{% url 'projects' %}">
                            <h3>{% trans 'Projects' %}</h3>
                        </md-button>
                        <nav-search></nav-search>
                        {% if user.is_authenticated %}
                        <md-button ng-href="{% url 'auth:logout' %}">
                            Log Out
                        </md-button>
                        {% endif %}
                        <md-menu class="md-secondary" md-position-mode="target-right target">
                            {% get_current_language as curr_lang %}
                            <md-button aria-label="Open Language Menu" ng-click="$mdMenu.open($event)">
                                {{ curr_lang|upper }}
                            </md-button>
                            <md-menu-content width="2" ng-mouseleave="$mdMenu.close()">
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for lang in languages %}
                                <!-- <md-menu-item><md-button>{{ lang.code|upper }}</md-button></md-menu-item> -->
                                <md-button ng-href="/{{lang.code}}/">{{ lang.code|upper }}</md-button>
                                {% endfor %}
                            </md-menu-content>
                        </md-menu>
                    </div>
                </md-toolbar>
            </md-content>
            {% block landing %}
            <div style="margin-top: 80px">
                <!-- This is to ensure that the content is offset when there's no landing -->
            </div>
            {% endblock %}
        </div>
        {% endblock header %}
    </header>
    <main flex layout="row" layout-align="space-around start">
        {% block media_scroller %}
            <div class="fixed-media" scroll-class scroll-offset="200" scroll-toggle-class="scrolling">
                <md-fab-speed-dial md-direction="up" md-open="showMediaFab" class="md-scale">
                    <md-fab-trigger>
                        <md-button aria-label="menu" class="md-fab">
                            <md-tooltip md-direction="down">{% trans 'Find me on social media' %}</md-tooltip>
                            <md-icon md-svg-src="img/icons/menu.svg" aria-label="menu"></md-icon>
                        </md-button>
                    </md-fab-trigger>
                    <md-fab-actions>
                        <md-button class="md-fab md-mini md-button md-ink-ripple" aria-label="Facebook" >
                            <md-tooltip md-direction="right"
                                md-autohide="false">Facebook
                            </md-tooltip>
                            <md-icon md-svg-src="img/icons/facebook.svg"></md-icon>
                        </md-button>
                        <md-button class="md-fab md-mini md-button md-ink-ripple" aria-label="LinkedIn">
                            <md-tooltip md-direction="right"
                                md-autohide="false">LinkedIn
                            </md-tooltip>
                            <md-icon md-svg-src="img/icons/linkedin.svg"></md-icon>
                        </md-button>
                        <md-button class="md-fab md-mini md-button md-ink-ripple" aria-label="GitHub">
                            <md-tooltip md-direction="right"
                                md-autohide="false">GitHub
                            </md-tooltip>
                            <md-icon md-svg-src="img/icons/github.svg"></md-icon>
                        </md-button>
                        <md-button class="md-fab md-mini md-button md-ink-ripple" aria-label="Mail">
                            <md-tooltip md-direction="right"
                                md-autohide="false">Mail
                            </md-tooltip>
                            <md-icon md-svg-src="img/icons/mail.svg"></md-icon>
                        </md-button>
                    </md-fab-actions>
                </md-fab-speed-dial>
            </div>
        {% endblock media_scroller %}
        {% block content %}
        {% endblock content %}
        {% block scroller %}
            <div class="fixed-scroller" scroll-class scroll-offset="200" scroll-toggle-class="scrolling">
                <sticky-scroll></sticky-scroll>
            </div>
        {% endblock scroller %}
    </main>
    <footer flex>
        <md-toolbar flex layout="column" layout-align="center center">
            <div layout="center center">
                <div class="md-subhead">
                    © 2017 Copyright: <a href="/"> Marcin Muszynski </a>
                </div>
            </div>
        </md-toolbar>
    </footer>
    <script type="text/javascript" src="{% static 'libs/angular/angular'|minified %}"></script>
    <script type="text/javascript" src="{% static 'libs/angular-resource/angular-resource'|minified %}"></script>
    <script type="text/javascript" src="{% static 'libs/angular-animate/angular-animate'|minified %}"></script>
    <script type="text/javascript" src="{% static 'libs/angular-aria/angular-aria'|minified %}"></script>
    <script type="text/javascript" src="{% static 'libs/angular-messages/angular-messages'|minified %}"></script>
    <script type="text/javascript" src="{% static 'libs/angular-material/angular-material'|minified %}"></script>
    <script type="text/javascript" src="{% static 'site/js/skeleton.js' %}"></script>
    <script type="text/javascript" src="{% static 'site/js/icons.js' %}"></script>
    {% include 'directives.html' %}
    {% block extra_js %}{% endblock extra_js %}
</body>
</html>